"
"
" Common {{{
" Basic
set antialias
set clipboard+=autoselect,unnamed cmdheight=1
set guioptions-=b guioptions-=e guioptions-=g guioptions-=l guioptions-=L guioptions-=m guioptions-=r guioptions-=R guioptions-=t guioptions-=T
set mouse=
set showtabline=1
set t_vb=
set winaltkeys=no
" Color
if getfsize(expand('%:p')) < 262144
    colorscheme kazuakim
endif
" Mapping
"  ESC
inoremap <silent> <Esc> <Esc>`^
"}}}
"
"
" OS type {{{
"  Window
function! KazuakiMSetFont(font) abort "{{{
    let s:KazuakiMFont += a:font

    if has("win32") || has ("win64")
        execute 'set guifont=Source_Code_Pro:h' . s:KazuakiMFont . ':cANSI'
    else
        execute 'set guifont=Ricty\ Diminished\ Discord\ Regular:h' . s:KazuakiMFont . ' macmeta'
    endif
endfunction "}}}
if has("win32") || has ("win64")
    let s:KazuakiMFont = 12
else
    let s:KazuakiMFont = 16
endif
call KazuakiMSetFont(0)

nnoremap <S-Down>  :<C-u>call KazuakiMSetFont(-1)<CR>
nnoremap <S-Up>    :<C-u>call KazuakiMSetFont( 1)<CR>
"}}}
