# vi: set ft=dockerfile:fdl=0:sts=4:sw=4:ts=4
#-------------------------------------------------------------------------------
FROM scratch
ADD centos-7-docker.tar.xz /

LABEL name="CentOS Base Image" \
    vendor="CentOS" \
    license="GPLv2" \
    build-date="20170605"

CMD ["/bin/bash"]
