languages:
  go:
    lint-command: 'go vet'
    lint-stdin: true
    lint-offset: 1
    format-command: 'goimports -w'
  #php:
  #  lint-command: 'php -l -d error_reporting=E_ALL -d display_errors=1 -d display_startup_errors=1 -d log_errors=0'
  #  lint-stdin: true
  #  lint-offset: 1
