# vi: set ft=ruby:
#-----------------------------------------------------------------------------------------------
# The most common configuration options are documented and commented below.
# For a complete reference, please see the online documentation at
#  https://docs.vagrantup.com.
#
# Every Vagrant development environment requires a box. You can search for boxes at
#  https://atlas.hashicorp.com/search.
#
# Repository List
#  @epel     http://ftp.riken.jp/Linux/fedora/epel
#  @remi     http://rpms.famillecollet.com/RPM-GPG-KEY-remi
#  @rpmforge http://apt.sw.be/RPM-GPG-KEY.dag.txt
#  @mysql    http://repo.mysql.com/RPM-GPG-KEY-mysql
#
#-----------------------------------------------------------------------------------------------
VAGRANTFILE_API_VERSION = 2
VAGRANTFILE_LOG         = "/var/log/vagrantfile.log"
ACCOUNT                 = "vagrant"
PROCESS_MAX             = 10
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  index = 0

  config.vm.box = "relativkreativ/centos-7-minimal"
  config.vm.network  "forwarded_port", guest: 80, host: 2223
  config.vm.provider "virtualbox" do |vb|
    vb.gui    = false
    vb.memory = "4096"
  end
  config.vm.provision "shell", inline: <<-SHELL
    echo "[ #{index = (( index +1 ))}/#{PROCESS_MAX} ]Set Environment ..." && \
      sudo touch #{VAGRANTFILE_LOG}                          && \
      sudo chown -R #{ACCOUNT}:#{ACCOUNT} #{VAGRANTFILE_LOG} && \
      echo "\tLOG:\t#{VAGRANTFILE_LOG}"                      && \
      HOME=/home/#{ACCOUNT}                                  && \
      echo "\tHOME:\t${HOME}"                                && \
    echo "[ #{index = (( index +1 ))}/#{PROCESS_MAX} ]Install key & repository ..." && \
      sudo rpm --import http://ftp.riken.jp/Linux/fedora/epel/RPM-GPG-KEY-EPEL-7                          >> #{VAGRANTFILE_LOG} && \
      sudo rpm -ivh http://ftp.riken.jp/Linux/fedora/epel/7/x86_64/e/epel-release-7-5.noarch.rpm          >> #{VAGRANTFILE_LOG} && \
      sudo rpm --import http://rpms.famillecollet.com/RPM-GPG-KEY-remi                                    >> #{VAGRANTFILE_LOG} && \
      sudo rpm -ivh http://rpms.famillecollet.com/enterprise/remi-release-7.rpm                           >> #{VAGRANTFILE_LOG} && \
      sudo rpm --import http://apt.sw.be/RPM-GPG-KEY.dag.txt                                              >> #{VAGRANTFILE_LOG} && \
      sudo rpm -ivh http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el7.rf.x86_64.rpm >> #{VAGRANTFILE_LOG} && \
      sudo rpm --import http://repo.mysql.com/RPM-GPG-KEY-mysql                                           >> #{VAGRANTFILE_LOG} && \
      sudo rpm -ivh http://dev.mysql.com/get/mysql-community-release-el7-5.noarch.rpm                     >> #{VAGRANTFILE_LOG} && \
    echo "[ #{index = (( index +1 ))}/#{PROCESS_MAX} ]YUM install & update ..." && \
      sudo yum clean all                                       >> #{VAGRANTFILE_LOG} && \
      sudo yum -y --enablerepo=epel,mysql,remi,rpmforge update >> #{VAGRANTFILE_LOG} && \
      sudo yum clean all                                       >> #{VAGRANTFILE_LOG} && \
      sudo yum -y --enablerepo=epel,mysql,remi,rpmforge install \
        colordiff           ctags \
        gcc                 git \
        htop                httpd \
        libcurl-devel       lynx \
        make                man-pages-ja  mysql-community-server \
        ncurses-devel       nmap-ncat \
        openssl             openssl-devel \
        perl                perl-core     perl-devel php php-devel pv python python-devel \
        readline            ruby          ruby-devel \
        screen              sqlite-devel \
        the_silver_searcher tmux          tree \
        wget \
        yum-cron \
        zlib-devel                                             >> #{VAGRANTFILE_LOG} && \
    echo "[ #{index = (( index +1 ))}/#{PROCESS_MAX} ]Set dotfiles ..." && \
      mkdir -p $HOME/work $HOME/.config/htop                                                                                                       && \
      git clone https://github.com/KazuakiM/dotfiles.git $HOME/work/dotfiles                          >> #{VAGRANTFILE_LOG} 2>> #{VAGRANTFILE_LOG} && \
      ln -sf $HOME/work/dotfiles/.bash_logout         $HOME/.bash_logout                                                                           && \
      ln -sf $HOME/work/dotfiles/.bash_profile        $HOME/.bash_profile                                                                          && \
      ln -sf $HOME/work/dotfiles/.bashrc              $HOME/.bashrc                                                                                && \
      cp -f  $HOME/work/dotfiles/.bashrc.local        $HOME/                                                                                       && \
      ln -sf $HOME/work/dotfiles/.ctags               $HOME/.ctags                                                                                 && \
      ln -sf $HOME/work/dotfiles/.dir_colors          $HOME/.dir_colors                                                                            && \
      ln -sf $HOME/work/dotfiles/.gitconfig.org       $HOME/.gitconfig                                                                             && \
      cp -f  $HOME/work/dotfiles/.gitconfig.local.org $HOME/.gitconfig.local                                                                       && \
      ln -sf $HOME/work/dotfiles/.gvimrc              $HOME/.gvimrc                                                                                && \
      ln -sf $HOME/work/dotfiles/.htoprc              $HOME/.config/htop/htoprc                                                                    && \
      ln -sf $HOME/work/dotfiles/.inputrc             $HOME/.inputrc                                                                               && \
      ln -sf $HOME/work/dotfiles/.mplayer             $HOME/.mplayer                                                                               && \
      cp -f  $HOME/work/dotfiles/.netrc.org           $HOME/.netrc                                                                                 && \
      ln -sf $HOME/work/dotfiles/.screenrc            $HOME/.screenrc                                                                              && \
      ln -sf $HOME/work/dotfiles/.tmux.conf           $HOME/.tmux.conf                                                                             && \
      ln -sf $HOME/work/dotfiles/.vim                 $HOME/.vim                                                                                   && \
      ln -sf $HOME/work/dotfiles/.vimrc               $HOME/.vimrc                                                                                 && \
      cp -f  $HOME/work/dotfiles/.vimrc.local         $HOME/                                                                                       && \
      ln -sf $HOME/work/dotfiles/.w3m                 $HOME/.w3m                                                                                   && \
      git clone https://github.com/Shougo/neobundle.vim.git $HOME/.vim/bundle/neobundle.vim           >> #{VAGRANTFILE_LOG} 2>> #{VAGRANTFILE_LOG} && \
      wget http://jp1.php.net/distributions/manual/php_manual_ja.tar.gz -O /tmp/php_manual_ja.tar.gz  >> #{VAGRANTFILE_LOG} 2>> #{VAGRANTFILE_LOG} && \
      tar zxvf /tmp/php_manual_ja.tar.gz -C $HOME/.vim/vim-ref                                        >> #{VAGRANTFILE_LOG} 2>> #{VAGRANTFILE_LOG} && \
      wget http://cs.sensiolabs.org/get/php-cs-fixer.phar -O $HOME/.vim/vim-php-cs-fixer/php-cs-fixer >> #{VAGRANTFILE_LOG} 2>> #{VAGRANTFILE_LOG} && \
      chmod a+x $HOME/.vim/vim-php-cs-fixer/php-cs-fixer                                                                                           && \
      php $HOME/work/dotfiles/src/phpDict.php                                                                                                      && \
      sh $HOME/work/dotfiles/src/htmlReference.sh                                                     >> #{VAGRANTFILE_LOG} 2>> #{VAGRANTFILE_LOG} && \
    echo "[ #{index = (( index +1 ))}/#{PROCESS_MAX} ]Install q ..." && \
      sudo rpm -ivh https://github.com/harelba/packages-for-q/raw/master/rpms/q-text-as-data-1.5.0-1.noarch.rpm >> #{VAGRANTFILE_LOG} && \
    echo "[ #{index = (( index +1 ))}/#{PROCESS_MAX} ]Install LuaJIT ..." && \
      git clone http://luajit.org/git/luajit-2.0.git /usr/local/src/luajit >> #{VAGRANTFILE_LOG} 2>> #{VAGRANTFILE_LOG} && \
      cd /usr/local/src/luajit                                                                                          && \
      make                                                                 >> #{VAGRANTFILE_LOG}                        && \
      make install                                                         >> #{VAGRANTFILE_LOG}                        && \
    echo "[ #{index = (( index +1 ))}/#{PROCESS_MAX} ]Install Composer ..." && \
      curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin >> #{VAGRANTFILE_LOG} && \
    echo "[ #{index = (( index +1 ))}/#{PROCESS_MAX} ]Install Vim ..." && \
      git clone https://github.com/vim/vim.git /usr/local/src/vim                                             >> #{VAGRANTFILE_LOG} 2>> #{VAGRANTFILE_LOG} && \
      cd /usr/local/src/vim                                                                                                                                && \
      sudo ln -s /usr/local/bin/luajit /usr/bin/luajit                                                                                                     && \
      sudo ./configure --disable-darwin --disable-netbeans --disable-selinux --disable-xim --disable-xsmp --disable-xsmp-interact --enable-cscope \
        --enable-fail-if-missing --enable-fontset --enable-luainterp --enable-multibyte --enable-rubyinterp --enable-perlinterp --enable-pythoninterp \
        --prefix=/usr/local --with-features=huge --with-ruby-command=/usr/bin/ruby --with-python-config-dir=/usr/lib64/python2.7/config --with-luajit \
        --with-lua-prefix=/usr/local                                                                          >> #{VAGRANTFILE_LOG}                        && \
      sudo make                                                                                               >> #{VAGRANTFILE_LOG}                        && \
      sudo make install                                                                                       >> #{VAGRANTFILE_LOG}                        && \
    echo "[ #{index = (( index +1 ))}/#{PROCESS_MAX} ]Update chown ..." && \
      sudo chown -R #{ACCOUNT}:#{ACCOUNT} /usr/local && \
      sudo chown -R #{ACCOUNT}:#{ACCOUNT} $HOME      && \
    echo "[ #{index = (( index +1 ))}/#{PROCESS_MAX} ]NeoBundleUpdate! (making now)..." && \
      echo "$ vagrant ssh"                                       && \
      echo "$ (LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib)" && \
      echo "$ vim -N -u $HOME/.vimrc -c 'try | NeoBundleUpdate! | finally | qall! | endtry' -U NONE -i NONE -V1 -e -s >> #{VAGRANTFILE_LOG} 2>> #{VAGRANTFILE_LOG}"
  SHELL
end

